-- Use to open terminal.
--function! OpenTerminal()
--    split term://zsh
--    resize 10
--endfunction
--let $TERMCWD = expand('%:p:h')
--nnoremap <leader>t :call OpenTerminal()<CR>cd $TERMCWD<CR>clear<CR>
--
--" Exit out of terminal.
--tnoremap <C-q> <C-\><C-n>:q!<CR>
--
--" Start terminal in insert mode.
--autocmd TermOpen * startinsert
--
--" Easily navigate between terminal and other panes.
--tnoremap <C-h> <C-\><C-n><C-w>h
--tnoremap <C-j> <C-\><C-n><C-w>j
--tnoremap <C-k> <C-\><C-n><C-w>k
--tnoremap <C-l> <C-\><C-n><C-w>l

