vim.api.nvim_create_augroup('init', {})

require('lib.global')
require('base.packer')
require('base.options')
require('base.theming')
require('base.commands')
require('base.maps')
require('base.netrw')
require('base.terminal')
require('base.tabline')
require('base.statusline')

require('plugins.nvim-lspconfig')
require('plugins.gitsigns')
require('plugins.nvim-autopairs')
require('plugins.nvim-cmp')
require('plugins.comment')
require('plugins.nvim-treesitter')
require('plugins.telescope')
--[[ require('plugins.nvim-tree') ]]
require('plugins.nvim-dap')
